### ISSUE TITLE
Corebird fails to start

### ISSUE THREAD

**Issue by jamiedbennett** [snapcrafters/corebird#20]
Corebird seems to have stopped working for me in the last week. On launch there is no window only the below error message that needs to be ^c out of.

    jamie@ubik:~$ corebird

    (corebird:17244): Gtk-WARNING **: Locale not supported by C library.
	    Using the fallback 'C' locale.

    (corebird:17244): Gtk-WARNING **: Theme parsing error: style.css:20:13: The 'icon-shadow' property has been renamed to '-gtk-icon-shadow'

    (corebird:17244): Gtk-WARNING **: Theme parsing error: style.css:231:16: The 'outline-radius' property has been renamed to '-gtk-outline-radius'

    (corebird:17244): Gtk-WARNING **: Theme parsing error: style.css:237:19: The :insensitive pseudo-class is deprecated. Use :disabled instead.

    (corebird:17244): Gtk-WARNING **: Theme parsing error: style.css:238:25: The :insensitive pseudo-class is deprecated. Use :disabled instead.

    (corebird:17244): Gtk-WARNING **: Theme parsing error: style.css:243:36: The :insensitive pseudo-class is deprecated. Use :disabled instead.

    (corebird:17244): corebird-WARNING **: Corebird.vala:377: Could not add window for account ''

    (corebird:17244): Gdk-CRITICAL **: gdk_window_get_window_type: assertion 'GDK_IS_WINDOW (window)' failed

    (corebird:17244): gspell-WARNING **: iso_639.xml: Failed to open file ?/usr/share/xml/iso-codes/iso_639.xml?: open() failed: No such file or directory

    (corebird:17244): gspell-WARNING **: iso_3166.xml: Failed to open file ?/usr/share/xml/iso-codes/iso_3166.xml?: open() failed: No such file or directory

    (corebird:17244): corebird-WARNING **: MainWindow.vala:492: Couldn't load window geometry for screen_name `jamiebennett'
    ^c
    jamie@ubik:~$ snap info core
    name:      core
    summary:   snapd runtime environment
    publisher: canonical
    contact:   snappy-canonical-storeaccount@canonical.com
    description: |
      The core runtime environment for snapd
    type:        core
    snap-id:     99T7MUlRhtI3U0QFgl5mXXESAiSwt776
    tracking:    candidate
    installed:   16-2.29.4.2 (3604) 87MB core
    refreshed:   2017-11-30 17:39:03 +0000 UTC
    channels:                       
      stable:    16-2.29.4.2 (3604) 87MB -
      candidate: 16-2.29.4.2 (3604) 87MB -
      beta:      16-2.30~rc3 (3700) 87MB -
      edge:      16-2.30~rc3 (3705) 87MB -

**Comment by popey** [comment]
Works here on 16.04 and 17.10. Are you in a wayland session? Find out with:-

    echo $XDG_SESSION_TYPE

**Comment by jamiedbennett** [comment]
No Wayland:

jamie@ubik:~$ echo $XDG_SESSION_TYPE
x11

Running on 17.10 as well.

**Comment by diddledan** [comment]
I can't replicate this on either Xorg or Wayland, both on 17.10. Does `snap list` show any "broken" snaps? what does `snap info corebird` show? Can you paste `snap version` too?

**Comment by jamiedbennett** [comment]
A reboot fixed the issue unfortunately.  I'll look out to see if it happens
again.

**Comment by flexiondotorg** [comment]
@jamiedbennett If the issue resurfaces and can provide additional information please re-open this issue.
