### ISSUE TITLE
"(core dumped)" when running corebird for the first time

### ISSUE THREAD

**Issue by OddBloke** [snapcrafters/corebird#21]
When running corebird for the first time, I see:

```
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  505k  100  505k    0     0  1341k      0 --:--:-- --:--:-- --:--:-- 1342k
/snap/corebird/88/bin/libopenh264-launch: line 49: 25599 Bad system call         (core dumped) bunzip2 "$H264DIR/libopenh264.so.bz2"
```

I don't see this on subsequent starts, but I do see it again whenever I refresh between channels (even if I've refreshed to that channel previously).

**Comment by diddledan** [comment]
it can be safely ignored. Unfortunately it's due to confinement rules which are preventing bunzip2 from running `chown` on an unzipped file. Luckily it happens *after* the file has been created so there isn't a problem with the file being corrupted.

**Comment by OddBloke** [comment]
Oh well. :crying_cat_face:
